import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';
import Main from '../components/main';
import Headermobile from '../components/headermobile';
import Footermobile from '../components/footermobile';
import Mainmobile from '../components/mainmobile';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Monochrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <Main></Main>

      <Footer></Footer>

      <Headermobile></Headermobile>

      <Mainmobile></Mainmobile>

      <Footermobile></Footermobile>
    </div>
  );

}
